fragcolor-xyz/shards

.gitmodules, CMakeLists.txt, include/chainblocks.h, include/ops.hpp, include/utility.hpp, src/core/blocks/casting.cpp, src/core/blocks/chains.cpp, src/core/blocks/core.cpp, src/core/blocks/core.hpp, src/core/blocks/flow.cpp, src/core/blocks/genetic.cpp, src/core/blocks/http.cpp, src/core/blocks/json.cpp, src/core/blocks/linalg.cpp, src/core/blocks/math.hpp, src/core/blocks/os.cpp, src/core/blocks/seqs.cpp, src/core/blocks/time.cpp, src/core/foundation.hpp, src/core/ops_internal.hpp, src/core/runtime.cpp, src/core/runtime.hpp, src/mal/CBCore.cpp, src/mal/Reader.cpp, src/mal/Types.h, src/tests/fib.clj, src/tests/general.clj
Valgrinding it and trying to improve things around..
also break things sadly :)
=> Optimizations

src/extra/shaders/implicit_shapes.h
First commit on my side.
A small shader ~~stolen~~ **borrowed** from ShaderToy
=> Devel issue4 implicit shapes

rust/rustfmt.toml, rust/src/block.rs, rust/src/blocks/casting.rs, rust/src/blocks/hash.rs, rust/src/blocks/mod.rs, rust/src/blocks/physics/forces.rs, rust/src/blocks/physics/rigidbody.rs
Format existing code using `cargo fmt` according to that config.
=> Add rust formatting config

src/core/blocks/core.hpp, src/core/blocks/flow.cpp, src/core/ops_internal.cpp, src/core/runtime.cpp
Some small fixes in Table usage
=> table-validation-fixes

rust/src/blocks/svg.rs, src/core/blocks/serialization.cpp
as well as flag premul svg image output
=> fix writepng and premultiplied alpha

.github/workflows/documentation.yml, .github/workflows/main.yml
Fix cloudflare sync.
Add error check.
=> Fix documentation workflow

deps/CMakeLists.txt
Windows started having issues with DXSDK_DIR apparently fixed in https://github.com/libsdl-org/SDL/commit/d9f70878f9fb531c5a9fc7adfa1fda456b77010c
Trying to fix some other issues at this SDL commit
=> Bump SDL & fix build

docs/samples/blocks/GUI/NextColumn.edn, docs/samples/blocks/General/Assoc.edn, src/core/blocks/core.cpp, src/extra/imgui.cpp
For both blocks
> Add sample code
> Add missing definition
> Modify parameter descriptions
=> Documentation for blocks Assoc & GUI.NextColumn

docs/samples/blocks/General/ChainLoader/ChainLoader.edn, docs/samples/blocks/General/Stop/Stop.edn, src/core/blocks/chains.cpp, src/core/runtime.cpp, src/mal/CBCore.cpp, src/tests/flows.clj
consider if chain is looped when running Inline in RunChain blocks
=> RunChain Inline & Looped support

.github/workflows/build-linux.yml
=> Run samples with coverage

.github/workflows/build-doc.yml, .github/workflows/build-ios.yml, .github/workflows/build-linux-docker.yml, .github/workflows/build-linux-valgrind.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-wasm.yml, .github/workflows/build-windows.yml, .github/workflows/main.yml, .github/workflows/test-linux-gpu.yml
Added a separate workflow that runs GPU tests on linux and collects/uploads coverage for it
-Guus
=> Testing self-hosted actions

.github/workflows/build-doc.yml
Modifies the `build-doc.yml` workflow to publish to GitHub Pages instead of NFT storage.
=> Publish documentation to GitHub pages

.gitignore, Cargo.lock, rust/Cargo.toml, rust/src/shards/casting.rs, rust/src/shards/substrate.rs, rust/src/types.rs
Adding From<T>, TryFrom<T> impl in Rust for Var for vector types with up to 4 elements.
https://github.com/fragcolor-xyz/shards/issues/263
**Has a test plan**
=> Rust var as i32

Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/shard.rs, rust/src/shards/casting.rs, rust/src/shards/chachapoly.rs, rust/src/shards/csv.rs, rust/src/shards/curve25519.rs, rust/src/shards/ecdsa.rs, rust/src/shards/eth.rs, rust/src/shards/gui.edn, rust/src/shards/gui.rs, rust/src/shards/http.rs, rust/src/shards/mod.rs, rust/src/shards/physics/forces.rs, rust/src/shards/physics/mod.rs, rust/src/shards/physics/rigidbody.rs, rust/src/shards/physics/shapes.rs, rust/src/shards/physics/simulation.rs, rust/src/shards/substrate.rs, rust/src/shards/svg.rs, rust/src/types.rs, src/tests/struct.clj
Since I'm fixing many things on the way let's open a new PR when we implement all the relative egui Shards @Kryptos-FR
=> Egui Integration Foundation

src/extra/CMakeLists.txt, src/extra/gfx.hpp, src/extra/gfx/main_window.cpp, src/extra/rust_interop.cpp, src/extra/rust_interop.hpp, src/gfx/egui/CMakeLists.txt, src/gfx/egui/build.rs, src/gfx/egui/egui_types.hpp, src/gfx/egui/input.cpp, src/gfx/egui/input.hpp, src/gfx/egui/renderer.cpp, src/gfx/egui/renderer.hpp, src/gfx/egui/rust_interop.hpp, src/gfx/egui/src/color_test.rs, src/gfx/egui/src/input.rs, src/gfx/egui/src/lib.rs, src/gfx/egui/src/renderer.rs, src/gfx/egui/src/standalone_test.rs, src/gfx/egui/test.cpp, src/gfx/loop.cpp, src/gfx/loop.hpp, src/gfx/rust/build/src/lib.rs, src/gfx/window.cpp, src/gfx/window.hpp
=> egui input

.github/workflows/build-windows.yml, rust/src/lib.rs, rust/src/shards/casting.rs, rust/src/shards/eth.rs, rust/src/shards/gui/containers/window.rs, rust/src/shards/http.rs, rust/src/shards/substrate.rs, rust/src/types.rs
removed `impl<'a> From<&'a str> for Var`
=> Rust str fixes

include/shards.h, include/utility.hpp, rust/src/core.rs, rust/src/shard.rs, rust/src/types.rs, src/core/runtime.cpp, src/extra/gfx.hpp
refactor and fix some leakage during compose (when error)
=> Compose fixes

Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/shards/date.rs, rust/src/shards/mod.rs, src/tests/bigint.clj, src/tests/rust.clj
Start adding Date formatting facilities.
=> Date.Format Shard

src/core/shards/core.cpp, src/tests/variables.clj
=> Add Reverse shard

include/shards.h, rust/src/shards/gui/containers/panels.rs, rust/src/shards/gui/containers/window.rs, rust/src/shards/gui/context.rs, rust/src/types.rs, src/core/foundation.hpp, src/core/shards/core.hpp, src/tests/failures.clj, src/tests/variables.clj
fails sporadically.. which is weird
=> Fixing Push/Table issues

docs/docs/contribute/code/building-shards.md
Added few additional lines after my experience on building Shards on WSL (Ubuntu).
=> Add WSL guide for building shards

src/core/shards/casting.cpp, src/core/shards/ws.cpp, src/tests/bigint.clj, src/tests/general.edn
couple of urgent fixes for testnet event
=> couple of urgent fixes

src/core/shards/ws.cpp, src/tests/ws.edn
=> more ws fixes

src/core/runtime.cpp, src/core/shards/core.hpp, src/core/shards/wires.cpp
=> more fixes

.github/workflows/build-linux-docker.yml, .github/workflows/build-linux.yml, .github/workflows/build-wasm.yml, .github/workflows/main.yml, .gitmodules, Cargo.lock, Cargo.toml, deps/CMakeLists.txt
=> shards-lang org rename

src/core/foundation.hpp, src/core/runtime.cpp, src/core/runtime.hpp, src/core/shards/wires.cpp
fix some recent changes that caused more issues
=> hotfix tick stop

.github/workflows/test-linux-gpu.yml, .gitignore, Cargo.lock, Cargo.toml, rust/Cargo.toml, rust/src/lib.rs, rust/src/shards/mod.rs, rust/src/shards/onnx.rs, rust/src/types.rs, src/tests/onnx.edn, src/tests/rust.clj, src/tests/struct.clj
Will squash. 
Needed by discord bot and in general cool
=> Testing building with tract-onnx

docs/samples/shards/UI/Button/2.edn, docs/samples/shards/UI/Checkbox/2.edn, docs/samples/shards/UI/Combo/2.edn, docs/samples/shards/UI/Hyperlink/2.edn, docs/samples/shards/UI/Int4Slider/2.edn, docs/samples/shards/UI/IntSlider/2.edn, docs/samples/shards/UI/Label/3.edn, docs/samples/shards/UI/Link/1.edn, docs/samples/shards/UI/Link/2.edn, docs/samples/shards/UI/RadioButton/2.edn, rust/src/shards/gui/containers/area.rs, rust/src/shards/gui/containers/window.rs, rust/src/shards/gui/misc/mod.rs, rust/src/shards/gui/misc/style.rs, rust/src/shards/gui/mod.rs, rust/src/shards/gui/widgets/button.rs, rust/src/shards/gui/widgets/checkbox.rs, rust/src/shards/gui/widgets/combo.rs, rust/src/shards/gui/widgets/hyperlink.rs, rust/src/shards/gui/widgets/label.rs, rust/src/shards/gui/widgets/link.rs, rust/src/shards/gui/widgets/mod.rs, rust/src/shards/gui/widgets/numeric_slider.rs, rust/src/shards/gui/widgets/radio_button.rs, rust/src/shards/gui/widgets/text_util.rs, src/tests/ui.edn
Some fixes mostly around styling:
- fix an issue with unset position on `UI.Area` and `UI.Window`
- add a `:Style` parameter on `UI.Label`, `UI.Button`, `UI.RadioButton`, sliders, `UI.Combo`, `UI.Hyperlink`
- fix `UI.Style` not working at top level
=> UI style fixes

rust/README.md, src/README.md
Adds two README files with some basic implementation details for creating new shards in `C++` or in `Rust`.
=> Add documentation about creating new shards

src/core/shards/core.cpp, src/tests/general.edn
=> Fix Issues with the `Erase` shard #316

.github/workflows/build-linux.yml, src/core/foundation.hpp, src/core/runtime.cpp, src/mal/SHCore.cpp, src/tests/pure.edn
=> add Pure and defpure

Cargo.lock, docs/samples/shards/UI/HexViewer/1.edn, rust/Cargo.toml, rust/src/shards/gui/widgets/hex_viewer.rs, rust/src/shards/gui/widgets/mod.rs, rust/src/types.rs
We had an hex viewer implemented with `ImGui`. Replace with a similar one implemented with `egui`.
**Test plan**
**Usage**
*See sample*
=> UI HexViewer

Cargo.lock, docs/samples/shards/UI/Grid/1.edn, docs/samples/shards/UI/Table/1.edn, docs/samples/shards/UI/Table/2.edn, docs/samples/shards/UI/Table/3.edn, rust/Cargo.toml, rust/src/shards/gui/layouts/grid.rs, rust/src/shards/gui/layouts/mod.rs, rust/src/shards/gui/layouts/table.rs, rust/src/shards/gui/widgets/text_util.rs, src/core/runtime.cpp
Adds `(UI.Grid)` and `(UI.Table)`.
**Details**
`(UI.Grid)` is a simple manual layout where widgets are set in a grid and a new row is created whenever `(UI.RowEnd)` is used.
`(UI.Table)` on the other end deals with sequence inputs and produces a row for each item in the sequence. Shards callback are given for each column of a row, and the columns' header and size are configurable.
=> UI grid and UI table

docs/details/shards/General/Remove.md
=> Fix: typos

Cargo.lock, rust/Cargo.toml, rust/src/shards/gui/layouts/table.rs, rust/src/shards/gui/mod.rs, rust/src/shards/gui/widgets/code_editor/syntax_highlighting.rs, src/gfx/egui/Cargo.toml
No behavior or visual changes. Just making work with the latest version.
It is a necessary update to then work on tabs using the latest `egui_dock`.
=> Update to egui 0.20.1

Cargo.lock, docs/generate.edn, docs/samples/shards/UI/MarkdownViewer/1.edn, docs/samples/shards/UI/MarkdownViewer/2.edn, docs/samples/shards/UI/MarkdownViewer/sample.md, rust/Cargo.toml, rust/src/shards/gui/containers/area.rs, rust/src/shards/gui/containers/panels.rs, rust/src/shards/gui/containers/window.rs, rust/src/shards/gui/context.rs, rust/src/shards/gui/layouts/space.rs, rust/src/shards/gui/mod.rs, rust/src/shards/gui/widgets/markdown_viewer.rs, rust/src/shards/gui/widgets/mod.rs
Adds a markdown viewer as a UI widget. Supports standard commonmark syntax.
=> UI markdown viewer

src/gfx/renderer.cpp
Fix for crash encountered with translated egui layers
=> Clamp clipping rectangles and ignore empty ones

.github/workflows/compress-strings.yml, src/core/compress-strings.edn
Example of workflow run: https://github.com/fragcolor-xyz/shards/actions/runs/3886110117
Example of PR created: #517 (note that commit message and title are now updated)
=> CI: add workflow to compress strings and create a PR

.github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .gitmodules, deps/CMakeLists.txt, include/dllshard.hpp, include/utility.hpp, src/core/CMakeLists.txt, src/core/foundation.hpp, src/core/ops_internal.cpp, src/core/runtime.cpp, src/core/runtime.hpp, src/core/shards/channels.cpp, src/core/shards/channels.hpp, src/core/shards/core.cpp, src/core/shards/core.hpp, src/core/shards/events.cpp, src/core/shards/http.cpp, src/core/shards/wires.cpp, src/core/shards/wires.hpp, src/mal/SHCore.cpp, src/tests/events.edn, src/tests/general.edn, src/tests/many.edn, src/tests/timing.edn
Start adding ENTT
For now mostly for events.
But other apps can use it further...
=> ENTT & events

src/core/shards/seqs.cpp, src/core/shards/strings.cpp, src/tests/strings.edn
split into Bytes.Join, String.Join
=> refactor Join

src/mal/SHCore.cpp, src/tests/flows.edn, src/tests/subwires.clj
split Def and Impl to allow to use wire variable inside self.
It's a kind of magic.
=> refactor "Wire" builtin

src/core/brancher.hpp, src/core/shards/wires.cpp
I required very similar implementation for the GFX.Feature generators, so I'm factoring out the implementation into some shared code
=> Factor out branch implementation

include/linalg_shim.hpp, include/shards.h, include/shards.hpp, include/utility.hpp, rust/Cargo.toml, rust/build.rs, rust/src/shards/onnx.rs, rust/src/shards/physics/mod.rs, rust/src/shards/substrate.rs, rust/src/types.rs, src/core/brancher.hpp, src/core/exposed_type_utils.hpp, src/core/foundation.hpp, src/core/ops_internal.hpp, src/core/params.hpp, src/core/runtime.cpp, src/core/runtime.hpp, src/core/shards/casting.cpp, src/core/shards/core.hpp, src/core/shards/linalg.cpp, src/core/shards/linalg.hpp, src/extra/gfx/shards_utils.hpp, src/extra/gfx/steps.cpp, src/mal/Core.cpp, src/mal/Environment.cpp, src/mal/Environment.h, src/mal/SHCore.cpp, src/tests/test_runtime.cpp
Various fixes and improvements I made while working on my graphics branch
=> Various fixes / improvements

src/core/CMakeLists.txt, src/core/foundation.hpp, src/core/tracking.cpp, src/core/tracking.hpp, src/extra/gfx/main_window.cpp, src/gfx/renderer.cpp
Add memory tracking for fundamental collections (SHSeq, SHTable, SHSet) for tracy profiler
=> Memory tracking

.github/workflows/build-doc.yml, .github/workflows/build-linux.yml, .github/workflows/build-macos.yml, .github/workflows/build-windows.yml, Cargo.lock, docs/samples/shards/FS/FileDialog/1.edn, docs/samples/shards/FS/FileDialog/2.edn, rust/Cargo.toml, rust/src/lib.rs, rust/src/shards/fs.rs, rust/src/shards/mod.rs, rust/src/types.rs
Basic implementation.
For now, only works 100% on Windows and macOS.
It should work on Linux for Desktop environments but won't for pure headless.
For wasm, we need to use rust async which I'm not sure how to make it work with our own coroutine.
=> File dialog

docs/samples/shards/UI/Variable/1.edn, rust/src/shards/gui/mod.rs, rust/src/shards/gui/widgets/mod.rs, rust/src/shards/gui/widgets/var_util.rs, rust/src/shards/gui/widgets/variable.rs, rust/src/types.rs
Basic editor to modify the value of a variable.
Currently supported types:
**Example**
```clj
(Setup
["hello" 1 3.14 (float2 1) [(float3 4)] [[[]]]] >= .my-var)
(UI
.ui-draw-queue
(UI.CentralPanel
(->
(UI.Variable .my-var)
(UI.Button "Dump" (-> .my-var (Log))))))
```
=> UI variable editor

docs/samples/shards/FS/SaveFileDialog/1.edn, rust/src/shards/fs.rs
Add `FS.SaveFileDialog` which works similarly to `FS.FileDialog`.
=> Save file dialog

cmake/Platform.cmake, src/core/runtime.cpp, src/gfx/drawable_processor_helpers.hpp, src/gfx/rust/CMakeLists.txt, src/log/CMakeLists.txt, src/log/log.cpp, src/tests/capture-logs.edn, src/tests/flows.edn, src/tests/test_runtime.cpp
- Some android related fixes
- Fix hashing of entire Var payload, which might contain uninitialized bytes when they come from rust
=> Daily Fixes

Cargo.lock, include/linalg_shim.hpp, rust/Cargo.toml, rust/src/shards/gui/mod.rs, rust/src/shards/gui/state.rs, src/core/shards/fs.cpp, src/extra/gfx/main_window.cpp, src/gfx/egui/input.cpp, src/gfx/window.cpp, src/gfx/window.hpp
- EGUI memory (window states)
- Window state
=> Add various state save/restore shards

src/core/shards/time.cpp, src/tests/time.edn
Regression from 1c3521b26a8a12e1652837222c1154705e9d29dc.
=> Fix Time.EpochMS

src/core/shards/fs.cpp, src/extra/CMakeLists.txt, src/extra/clipboard.cpp, src/extra/runtime.cpp, src/tests/general.edn
- FS shards
- Clipboard shards
=> Various changes

docs/samples/shards/Time/ToString/1.edn, src/core/shards/time.cpp
Convert time to a human readable string.
**Examples**
```clj
0 (Time.ToString) (Log) ; 0s
59 (Time.ToString) (Log) ; 59s
60 (Time.ToString) (Log) ; 1m:0s
61 (Time.ToString) (Log) ; 1m:1s
(Time.EpochMs) (Time.ToString :Millis true) (Log) ; 53y:84d:13h:26m:28s
```
=> Add Time.ToString

docs/docs/contribute/index.md, docs/docs/learn/index.md, docs/docs/learn/shards/index.md, docs/docs/reference/index.md, docs/docs/reference/shards/enums/index.md, docs/docs/reference/shards/index.md, docs/docs/reference/shards/lisp/index.md
Expanded on the landing pages for the "Reference", "Learn" and "Contribute" segments.
=> Docs landing pages

src/anim/anim.cpp, src/core/runtime.cpp, src/core/shards/core.hpp, src/core/shards/time.cpp, src/core/shards/time.hpp, src/extra/gfx/main_window.cpp, src/extra/inputs.cpp, src/extra/inputs.hpp
- Add IsKeyDown
- Add Time.Delta
- Improve some error messages
=> More various changes

src/extra/gfx/shader/flow_shards.cpp, src/extra/gfx/shader/translator_utils.hpp
Fix the If shard so it can be used fully.
Here is an example:
https://github.com/fragcolor-xyz/rare-examples/blob/fd6f0310a51c09bc8edeebc3469b5bee4b16ca06/gfx/gfx-master-dither.edn#L37
=> Support non-passthrough If in shader

docs/docs/reference/shards/overview/index.md
- Added a segment on Conversion shards
=> Overview sections

docs/samples/shards/UI/ListBox/3.edn, rust/src/shards/gui/context.rs, rust/src/shards/gui/widgets/listbox.rs, rust/src/shards/gui/widgets/mod.rs, rust/src/types.rs
Add selection callbacks to list box
=> Add ListBox selection callbacks

docs/docs/learn/shards/primer/coding-with-shards.md
Quick fixes in 'Coding with Shards' docs: https://docs.fragnova.com/learn/shards/primer/coding-with-shards/
=> Quick fixes in 'Coding with Shards' docs

cmake/Root.cmake, cmake/ShardsTools.cmake, cmake/Tools.cmake, include/shards/shards.swift, shards/gfx/features/base_color.hpp, shards/tests/gfx-generated.edn
Manually allow specifying shards binary for usage in shards_build
=> Fix shards_build when cross compiling

shards/modules/physics/src/forces.rs, shards/modules/physics/src/lib.rs, shards/modules/physics/src/rigidbody.rs, shards/modules/physics/src/shapes.rs, shards/rust/src/util.rs, shards/tests/physics.edn
- Add Torque/Force/AngularImpulse
- Add Mass settings for physics shapes
- Cleanup some internals & rewrite with new shard macros
=> Add some new physics functionality

.github/workflows/build-linux.yml
=> Test fix linux coverage

shards/modules/fs/Cargo.toml, shards/modules/fs/src/lib.rs, shards/rust/src/types.rs, shards/tests/general.shs, shards/tests/notify.shs
=> Add FS.Watch

shards/modules/sqlite/sqlite.cpp
=> use shared lock to avoid connection creation issues in sqlite

include/shards/shards.hpp, shards/modules/core/Cargo.toml, shards/modules/core/core.cpp, shards/modules/core/core.hpp, shards/modules/core/src/uuid.rs, shards/modules/core/wires.cpp, shards/modules/network/network.cpp, shards/tests/crypto.shs, shards/tests/test_runtime.cpp
=> Add rs-snowflake crate and implement

shards/modules/network/network.cpp
=> Fixes in networking shards

shards/modules/sqlite/sqlite.cpp
=> Add transactionMutex to Connection struct

include/shards/common_types.hpp, shards/modules/core/seqs.cpp, shards/tests/hello.shs
=> Add Zip shard for combining sequences
