- docs/mkdocs.yml
Turns out, enabling it was not difficult as long as you can figure out it has to be enabled in the `mkdocs.yml` file.
See: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
----
Fixes #76
> Enable syntax hightlighting for code blocks in the documentation

- src/mal/CBCore.cpp
Keywords start with a ':' while simple keys are quoted strings.
When used as key in a map, quoted strings need to be "unescaped", and keywords need to only lose the leading ':' character.
Fixes #91
> Fix incorrect trimming of keywords when used as key

- src/extra/bgfx.cpp
Fixes a crash when creating a BGFX window on linux.
It's calling XGetXCBConnection(nullptr) if the display is not set in the platform data
Simplified SDL_GetNativeWindowPtr definition a bit to remove the specific types, since they're not used anyways
> Set display in bgfx platform data

- src/mal/CBCore.cpp
The idea is to be consistent with the following rule:
- built-ins are lowercase and interpreted by mal (hence they don't need to run inside a chain)
- blocks are Capitalized and they do need to run in the context of a chain
This should help writing code by having a visual guide (sometimes it is complicated to mix blocks and built-ins).
However, since some basic types have existed for a while with a capitalized letter, we know have uppercase overrides for backward compatibility and convenience. It is a slight deviation from the above rule but since it only concerns basic structures, it shouldn't matter too much.
> Make built-in types lowercase

- .gitmodules
- src/core/blocks/chains.cpp
- src/core/blocks/core.hpp
- src/core/blocks/edn.cpp
- src/core/blocks/http.cpp
- src/core/blocks/json.cpp
- src/core/blocks/wasm.cpp
- src/core/edn/print.hpp
- src/core/edn/read.hpp
- src/core/foundation.hpp
- src/core/ops_internal.cpp
- src/core/runtime.cpp
- src/core/runtime.hpp
- src/extra/desktop.win.cpp
- src/extra/gltf.cpp
- src/extra/imgui.cpp
- src/extra/runtime.cpp
- src/mal/CBCore.cpp
- src/mal/Reader.cpp
- src/mal/Types.cpp
- src/mal/Validation.cpp
- src/tests/test_extra.cpp
- src/tests/test_runtime.cpp
Some code-only changes extracted from the cmake branch.
Most of these were encountered when compiling with clang.
It doesn't fix everything but it compiles and doesn't crash on startup
- Change wasm3 module to https://github.com/chainblocks/wasm3.git (main branch)
- Global initialization order fix for clang
- Missing header  \<optional\>
- Missing inline in header function
- Explicit usage of CBType values where they're ambiguous
- EXPORT macro in source file
- Don't install signal handlers when a debugger is attached
- make "Overriding enum type" a debug log so it doesn't show up on stdout during test discovery
> Various fixes guus

- .github/workflows/documentation.yml
- .github/workflows/main.yml
- use a matrix for Debug/Release as well as 32/64bits
- split build and test
It should make the documentation workflow a bit faster as we skip the tests.
> Refactor CI jobs for Windows

- .github/workflows/documentation.yml
- .github/workflows/main.yml
* Add a retry mechanism when publishing to NFT storage or updating Cloudflare.
* Use a caching action for rust, only enabled during a `pull_request` event. A `push` will trigger a full build without cache.
> Workflow retry

- .github/workflows/main.yml
- src/tests/audio.edn
Files comes from https://commons.wikimedia.org/wiki/File:Ode_to_Joy.ogg (public domain)
> Replace file used for audio testing

- .github/workflows/main.yml
Executables built was the cache is active have been checked to work on Windows. So we will try to keep the cache always on except on manually triggered workflows so that we have a workaround just in case.
> Disable the rust cache only on manual workflow

- .github/workflows/documentation.yml
- .github/workflows/main.yml
- src/tests/infos_docs.edn
Save the output logs of the samples and inject them into the documentation, as a separate tab next to the sample code.
> Doc: display sample's output

- docs/docs/functions/macros.md
- docs/docs/functions/misc.md
Add description and code samples for the following functions:
> `defchain`
> `defnode`
> `defloop`
> `run`
> `schedule`
> Enhance documentation for existing and undocumented functions

- src/core/blocks/strings.cpp
- src/tests/general.edn
`(ParseInt)` should be able to parse numbers that fit inside a 64-bit integer. Currently it only works up to 32-bit.
**Test plan**
> Fix ParseInt for 64-bit values

- docs/samples/blocks/General/ForEach/1.edn
- docs/samples/blocks/General/ForEach/2.edn
- docs/samples/blocks/General/Log/1.edn
- docs/samples/blocks/General/Match/1.edn
- docs/samples/blocks/General/Match/2.edn
- docs/samples/blocks/General/Match/3.edn
- docs/samples/blocks/General/Match/4.edn
- docs/samples/blocks/General/Match/5.edn
- docs/samples/blocks/General/Match/6.edn
- docs/samples/blocks/General/Msg/1.edn
- docs/samples/blocks/General/RTake/1.edn
- docs/samples/blocks/General/Slice/1.edn
- docs/samples/blocks/General/Sub/1.edn
- docs/samples/blocks/General/Sub/2.edn
- docs/samples/blocks/General/Take/1.edn
Remove the boilerplate `chain/loop` and `node` statements from the sample code of blocks.
Fixes #229
> Remove boilerplate statements from the samples

- .github/workflows/build-ios.yml
- .github/workflows/build-linux-docker.yml
- .github/workflows/build-linux-valgrind.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-wasm.yml
- .github/workflows/build-windows.yml
- .github/workflows/documentation.yml
- .github/workflows/main.yml
This PR adds separate workflows for building on `Windows`, `Linux`, `macOS`, `iOS` and `Wasm` platforms.
Those workflows can either be triggered manually, in which case they present the caller a few options such as building in Debug or Release mode ; or they can be called from the main CI workflow.
Eventually they should be callable from other repositories from the same org. There could be some issues with secrets not being shared which we will need to review later.
**Test plan**
> CI workflow split

- include/shards.hpp
- src/core/params.hpp
- src/extra/gfx/gltf.cpp
- src/extra/gfx/mesh.cpp
Add a set of macros to define parameters quickly.
Usage:
```cpp
class ShardName {
PARAM_VAR(_varName0, "DisplayName", "Help text", {Types});
// = Var _varName0;
PARAM_PARAMVAR(_varName1, "DisplayName", "Help text", {Type::VariableOf(Types)});
// = ParamVar _varName1; 
PARAM(ShardsVar, _varName2, "DisplayName", "Help text", {Types});
// = ShardsVar _varName2;
PARAM_IMPL(ShardName, PARAM_IMPL_FOR(_varName0), PARAM_IMPL_FOR(_varName1), PARAM_IMPL_FOR(_varName2));
// implements parameters()/getParam()/setParam()
// (and defines a static internal getIterableParams() that can be used to iterate over parameters)
// Automatically calls warmup/cleanup for parameters that implement it (e.g. ParamVar/ShardsVar)
void warmup(SHContext *context) { PARAM_WARMUP(context); }
void cleanup() { …
```
> C++ shard parameter macros 

- .gitmodules
- deps/CMakeLists.txt
Bundled boost into a source archive that doesn't contain tests/docs/unused modules (9.62 MB)
Check the dep branch for the build/package script.
Pushing a tag to that repo wil automatically create a release that can be linked to inside FetchContent_Declare
https://github.com/chainblocks/boost/commit/e11da3be380e29c5021912816e293c73127960f3
> Use boost source archive

- rust/src/shards/browse.rs
- rust/src/shards/casting.rs
- rust/src/shards/chachapoly.rs
- rust/src/shards/curve25519.rs
- rust/src/shards/ecdsa.rs
- rust/src/shards/eth.rs
- rust/src/shards/gui/containers/panels.rs
- rust/src/shards/gui/containers/window.rs
- rust/src/shards/gui/context.rs
- rust/src/shards/gui/util.rs
- rust/src/shards/gui/widgets/button.rs
- rust/src/shards/gui/widgets/label.rs
- rust/src/shards/hash.rs
- rust/src/shards/http.rs
- rust/src/shards/physics/forces.rs
- rust/src/shards/physics/queries.rs
- rust/src/shards/physics/rigidbody.rs
- rust/src/shards/physics/shapes.rs
- rust/src/shards/substrate.rs
- rust/src/types.rs
`ParamVar::get()` now returns a `&Var` instead of `Var` which created a copy.
This should make it a bit more efficient since a lot of time we get it in order to convert it into another value:
```rust
let text: &str = self.label.get().as_ref().try_into()?;
// can be simplified to
let text: &str = self.label.get().try_into()?;
```
In the other cases where we do need to get a `Var` we can make an explicit copy by dereferencing:
```rust
let simulation: Var = *self.simulation.get();
```
> ParamVar get returns a reference

- rust/src/shards/gui/containers/panels.rs
- rust/src/shards/gui/containers/window.rs
- rust/src/shards/gui/context.rs
- rust/src/shards/gui/mod.rs
- rust/src/shards/gui/widgets/button.rs
- rust/src/shards/gui/widgets/mod.rs
- rust/src/shards/gui/widgets/text_input.rs
- rust/src/shards/http.rs
Implement `UI.TextInput` (single line for now).
It supports having a mutable or immutable initial value. In case a non-existing variable is given, it will expose it.
```clj
;; const string
(UI.TextInput "You can't edit this!")
;; immutable variable
"Hello World!" = .imm
(UI.TextInput .imm)
;; mutable variable
"Lorem ipsum" >= .mut
(UI.TextInput .mut)
;; exposing a new string variable
(UI.TextInput .new)
```
Manipulating the `dyn TextBuffer` is optimized to only clone when the string capacity is not sufficient. Otherwise it does pointer arithmetic to move slices of memory around.
> Egui text input

- src/core/shards/core.hpp
You could Update a Push table breaking it's memory integrity
> ensure Update is also isPushTable aware

- cmake/Root.cmake
- deps/CMakeLists.txt
- src/core/CMakeLists.txt
- src/core/runtime.cpp
- src/extra/CMakeLists.txt
- src/gfx/CMakeLists.txt
- src/gfx/context.cpp
- src/gfx/egui/renderer.cpp
- src/gfx/log.hpp
- src/gfx/renderer.cpp
- src/gfx/tests/data.cpp
- src/gfx/tests/sandbox.cpp
- src/gfx/tests/test_shader.cpp
- src/log/CMakeLists.txt
- src/log/log.cpp
- src/log/log.hpp
- src/mal/SHCore.cpp
- Move some of the logger setup code to a separate "module"
- Automatically grab runtime log level from a `LOG_<logger_name>=debug/trace/info/etc.` environment variable
- Examples:
- `LOG_GFX=debug` debug output from graphics enabled
- `LOG_shards=trace` trace logging from shards enabled
- The behavior of compiling out DEBUG/TRACE logs in release builds is still intact so trying to enabled them does nothing unless the log calls were outside of macros
Seems to close https://github.com/fragcolor-xyz/shards/issues/272 too
> Move logging setup code. Add runtime log levels

- rust/src/core.rs
- rust/src/types.rs
- src/core/foundation.hpp
Add support for declaring shards enum in rust.
There are two macros: `shenum!`  and `shenum_types`. The first one is very similar to what `bitflags!` was doing, except it doesn't generate operators for now. The second one declares the various `Type` that are required if we want to use the enum as input/output or parameter type.
Fixes #366.
> Rust shards enum

- rust/src/lib.rs
- rust/src/shard.rs
Add two macros: `decl_override_activate` called during `compose`, and `impl_override_activate` that creates an `extern "C"` function that can be called from the C++ side.
Typical usage:
```rust
impl Shard for OverrideTest {
fn hasCompose() -> bool {
true
}
fn compose(&mut self, data: &InstanceData) -> Result<Type, &str> {
match data.inputType.basicType {
SHType_Float => decl_override_activate! {
data.activate = OverrideTest::float_activate;
},
SHType_Int => decl_override_activate! {
data.activate = OverrideTest::int_activate;
},
_ => (),
}
Ok(data.inputType)
}
fn activate(&mut self, _context: &Context, _input: &Var) -> Result<Var, &str> {
Err("Invalid input type")
}
}
impl OverrideTest {
fn activateFloat(&mut self, _context: &Context, input: &Var) -> Result<Var, &str> {
Ok(*input)
}
fn …
```
> Add macros to override the activate function

- src/mal/Core.cpp
Some C++ runtimes don't support (argsEnd - argsBegin) if argsBegin is the end iterator
std::distance works correctly in all cases
> Replace iterator math with std::distance

- Cargo.lock
- rust/Cargo.toml
- rust/src/shards/gui/widgets/image.rs
- rust/src/shards/gui/widgets/image_button.rs
- rust/src/shards/gui/widgets/text_input.rs
- rust/src/types.rs
- src/gfx/egui/Cargo.toml
- src/gfx/egui/src/color_test.rs
- src/gfx/egui/src/input.rs
Implement `TextBuffer` trait directly on `Var`.
Remove workaround that was using the `VarTextBuffer` enum.
Fix code following egui update.
> Update egui to 0.19.0

- .github/workflows/test-linux-gpu.yml
- rust/src/lib.rs
- rust/src/shards/gui/containers/area.rs
- rust/src/shards/gui/containers/panels.rs
- rust/src/shards/gui/containers/window.rs
- rust/src/shards/gui/context.rs
- rust/src/shards/gui/mod.rs
- rust/src/shards/gui/util.rs
- rust/src/shards/gui/widgets/image.rs
- rust/src/shards/physics/mod.rs
- rust/src/shards/substrate.rs
- rust/src/types.rs
- src/tests/ui-nested.edn
Makes the egui context exposed variable a stack.
This way we can have claymore UI host user scripts containing it's own UI.
Additionally I want to make some additional things available within the new `Context` struct, mainly to be able to map a region inside egui back into window coordinates
> UI Context stack & 4 character constants

- Cargo.lock
- docs/samples/shards/UI/CodeEditor/1.edn
- rust/Cargo.toml
- rust/src/shards/gui/mod.rs
- rust/src/shards/gui/widgets/code_editor.rs
- rust/src/shards/gui/widgets/code_editor/mod.rs
- rust/src/shards/gui/widgets/code_editor/syntax_highlighting.rs
- rust/src/shards/gui/widgets/mod.rs
A `TextInput` with support for syntax highlighting.
It is currently behind a `"code_editor"` feature flag. We might decide to have it enabled by default (as part of `"shards"`) or only when building an app such as claymore.
Uses the `Syntech` crate and the current implementation is mainly based on the `egui_demo_lib` from the `egui` repository for the layouting part.
---
Part of fragcolor-xyz/management#31
> UI code editor

- cmake/Rust.cmake
Fix for building tract-linalg for android target
> Override cargo AR when Android NDK is used

- .github/workflows/build-doc.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-wasm.yml
- .github/workflows/build-windows.yml
`Node 12` is deprecated and causing warnings which could soon become errors.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Swatinem/rust-cache, actions/upload-artifact
> Upgrade some CI actions

- docs/docs/docs/shards/GUI/index.md
- docs/includes/deprecated.md
- src/extra/imgui.cpp
- src/tests/infos-docs.edn
`ImGui`-based shards (prefixed by `GUI`) have mostly be replaced by `egui`-based one (prefixed by `UI`). Mark them as obsolete and display a warning in the API documentation.
> Mark GUI shards as deprecated

- .github/workflows/build-doc.yml
- .github/workflows/build-ios.yml
- .github/workflows/build-linux.yml
- .github/workflows/build-macos.yml
- .github/workflows/build-wasm.yml
- .github/workflows/build-windows.yml
- .github/workflows/codecov.yml
- .github/workflows/test-linux-gpu.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> CI: set-output is deprecated

- .github/workflows/main.yml
CI can still be triggered manually won't run when pushing new commits to a draft PR.
> Don't run CI on draft PR

- include/number_types.hpp
- src/core/number_types.cpp
- src/core/shards/bigint.cpp
- src/core/shards/casting.cpp
- src/core/shards/casting.hpp
- src/core/shards/linalg.cpp
- src/core/shards/linalg.hpp
- src/core/shards/math.hpp
- src/core/shards/math_ops.hpp
- src/mal/SHCore.cpp
- src/tests/bigint.clj
- src/tests/casting-numbers.edn
- src/tests/general.edn
Some changes I needed while working on the shader translator.
This make Float2/3/4 accept variables, e.g.:
```clojure
(Float4 0.0 0.0 .z .w) >= .my-float-4
(Float4 .all-4-values) >= .my-float-4-2
```
Some internal changes to make more combinations of math operations possible and remove duplication of applying operations between sequences
Performance note: everything is templated and the result is the same as when writing out the switch statements as done previously.
> Vector constructors & more generic math implementations

- src/core/shards/random.cpp
**Summary**
The variable given to the `:Max` parameter could be uninitialized and produce garbage results.
**Details**
Consider this code:
```clj
(defwire test-wire
(RandomInt :Max .total) >= .left-index (Log "left")
(RandomInt :Max .total) >= .right-index (Log "right"))
```
This compiles, executes but produces arbitrary values.
Another case, where the variable does exist in the parent wire but is not explicitly required also produced arbitrary values, despite the max being (apparently defined):
```clj
(defwire test-wire
;; .total ;; uncomment this to get it to work 
(RandomInt :Max .total) >= .left-index (Log "left")
(RandomInt :Max .total) >= .right-index (Log "right"))
(defwire base-wire
10 >= .total
(Branch [test-wire]))
(defmesh main)
(schedule main base-wire)
(run main)
``` …
> Fix RandomInt/Float requiring the variable to be initialized

- src/core/shards/linalg.hpp
- src/core/shards/math.hpp
- src/tests/linalg.clj
Accidentally returned the wrong output type when using (Math.Length), etc.
> Unary vector operators fix

- docs/samples/shards/General/Log/2.edn
- docs/samples/shards/General/Maybe/1.edn
- docs/samples/shards/General/Maybe/2.edn
- docs/samples/shards/General/Msg/2.edn
- include/shardwrapper.hpp
- include/utility.hpp
- rust/src/shards/gui/mod.rs
- rust/src/shards/gui/widgets/mod.rs
- rust/src/types.rs
- src/core/runtime.cpp
- src/core/shards/flow.cpp
- src/core/shards/logging.cpp
- src/core/shards/logging.hpp
- src/core/shards/math.hpp
- src/core/shards/random.cpp
- src/core/shards_macros.hpp
- src/mal/SHCore.cpp
```clj
42 (Log "prefix") ; default LogLevel.Info
-1 (Log "ERROR" LogLevel.Error)
(Msg "Trace me" LogLevel.Trace)
(Msg "TODO" LogLevel.Debug)
(Msg "That's incorrect" :Level LogLevel.Warning)
```
In addition, logs are now displayed from `Maybe` else clause when silent:
```clj
; before
[0]
(Maybe
(-> (Take 1))
(-> (Msg "Cannot retrieve item at index 1"))
:Silent true)
;; nothing displayed
; after
[0]
(Maybe
(-> (Take 1))
(-> (Msg "Cannot retrieve item at index 1" :Level LogLevel.Error)
:Silent true)
;; [error] [2022-11-18 14:48:26.889] [T-33400] [logging.cpp::101] [main-wire] Cannot retrieve item at index 1
```
> Allow to set log level on Msg and Log

- deps/CMakeLists.txt
Shouldn't be required on platforms that don't have `patch` command by default. It's also only required for XCode
> Only libressl patch for XCode

- src/core/shards/wires.hpp
- src/tests/failures.clj
- src/tests/flows.edn
- src/tests/ipfs.edn
Changed Do behaviour to propagate failures to the parent wire
Due to this I uncovered a failure in an IPFS upload in flows.edn, moved it out of there for now.
> Propagate Do failures

- .gitmodules
- deps/CMakeLists.txt
- src/gfx/CMakeLists.txt
- src/gfx/context.cpp
- src/gfx/renderer.cpp
- src/gfx/rust/CMakeLists.txt
- src/gfx/rust/gfx/Cargo.lock
- src/gfx/rust/gfx/Cargo.toml
- src/gfx/rust/gfx/src/lib.rs
- src/gfx/texture.cpp
Worked on this a while back but never finished it, let's merge it.
The way you use it:
- Grab the profiler UI from https://github.com/wolfpld/tracy/releases (Use 0.9 for the currently library version)
- Build shards with TRACY_ENABLE=ON (-D on CMake configure or edit cache)
- Use the tracy API from c++ (`#include <tracy/Tracy.hpp>`)
It works from rust too, though for now only from the `gfx` crate, because it needs the initialization to be done from rust. After initialization C++ & rust share the state though.
> Tracy profiler suport

- src/extra/gfx/main_window.cpp
Easy enough, since wire is already exposed during compose, I can just extend the stack size.
> MainWindow compose stack size

- docs/generate.edn
- rust/src/shards/gui/containers/mod.rs
- rust/src/shards/gui/properties.rs
- rust/src/shards/gui/widgets/plots/mod.rs
- rust/src/types.rs
- src/mal/SHCore.cpp
Automatically create links to the corresponding enum description page from the API pages.
Also support writing the enum description in rust code.
**Syntax**
```rust
shenum! {
struct UIProperty {
[description("Returns the remaining space")]
const RemainingSpace = 0x0;
}
struct UIPropertyInfo {}
}
```
It resembles the macro syntax but without the `#`. This has two advantages:
- clearly show that it is not a dedicated macro: it is just a syntax sugar interpreted by the `shenum!` macro itself
- allow to still attach other macros individually to enum values if needed:
```rust
shenum! {
struct UIProperty {
[description("Returns the remaining space")]
#[MyMacro)]
const RemainingSpace = 0x0;
}
struct UIPropertyInfo {}
}
```
Note: it is also mandatory on all enum values. So at the …
> Documentation: enums

- src/gfx/drawable_processors/mesh_drawable_processor.hpp
Performance for running the windows tests in the software rasterizer seems to have degraded after #500 (Vulkan seems unaffected)
Comparing job [6658454962](https://github.com/fragcolor-xyz/shards/actions/runs/3898687960/jobs/6658454962) to [6669771237](https://github.com/fragcolor-xyz/shards/actions/runs/3903338722/jobs/6669771237)
> Fix D3D12 warp performance

- src/core/shards/core.hpp
- src/mal/SHCore.cpp
Log when a frame takes too long but only do it at most every `1000` frames (regardless of actual time rate).
Applies to both the main loop of a wire running on a mesh, and to the specific repeat loop of `Once` shard.
> Log slow ticks at most once every 1000

- Cargo.lock
- rust/Cargo.toml
Following the dependabot alert, don't use the old version of `time` as a dependency for `chrono`.
References
- https://github.com/fragcolor-xyz/shards/security/dependabot/4
- https://github.com/chronotope/chrono/issues/876
- https://docs.rs/crate/chrono/0.4.20/features (page is not available for 0.4.19).
> Don't use oldtime feature with chrono crate

- src/core/foundation.hpp
- src/core/runtime.cpp
- src/core/shards/casting.cpp
- src/core/shards/wires.cpp
Allow wires (especially valid for pure ones) to have Any type as input if Expect is the first shard
> Any type as input if Expect is the first shard

- rust/src/core.rs
Print a pretty-log for `Var` to help debugging.
**Rationale**
`Debug` trait on `SHVarPayload` cannot be implemented automatically because it is an `unsafe` union. And transitively, `Debug` is also not automatically implemented for `SHVar`.
**Additional details**
Here are a few examples.
**SHEnum**
```
Var {
payload: SHEnum {
value: 1,
vendorId: 1718772071,
typeId: 1819240268,
},
valueType: 2,
innerType: 0,
..
},
``` 
**SHInt2**
```
Var {
payload: [1, 2],
valueType: 5,
innerType: 0,
..
},
```
**SHColor**
```
Var {
payload: SHColor { r: 255, g: 128, b: 0, a: 128 },
valueType: 14,
innerType: 0,
..
},
```
**SHBytes**
```
Var {
payload: SHBytes {
value: 0x21efe4e7320,
size: 3,
capacity: 3,
},
valueType: 51,
innerType: 0,
..
}
```
Note: the bytes value is not interpreted. …
> Implement Debug trait for SHVar

- rust/src/shards/http.rs
- src/core/shards/casting.hpp
- src/core/shards/flow.hpp
- src/core/shards/fs.cpp
- src/core/shards/genetic.hpp
- src/core/shards/http.cpp
- src/core/shards/seqs.cpp
- src/core/shards/serialization.cpp
Let's the shard declare both as potential output types.
I think this should be the idiomatic way to declare input/output types, list all potential types and only fixup during compose if necessary. And as a bonus, it makes introspection easier (for generating the doc as well as with the new shard editor).
> Fixup output type during compose

- src/extra/gfx.cpp
- src/gfx/render_graph.hpp
- src/gfx/renderer.cpp
- src/gfx/renderer.hpp
This allows having multiple GFX.Render calls overlay on the same color buffer for now without having to merge the render graphs
> Add hack to treat Render outputs as cleared/written

- .github/workflows/build-doc.yml
- src/log/log.cpp
- src/log/log.hpp
Would help simplify the logs, for instance when running the documentation sample.
**before**
```
./build/Release/shards docs/samples/run-sample.edn --file shards/Assert/is/2.edn
```
```
[error] [2023-02-14 20:31:56.037] [T-23040] [assert.cpp::66] Failed assertion Is, input: 7 expected: 8
[error] [2023-02-14 20:31:56.038] [T-23040] [runtime.cpp::715] Shard activation error, failed shard: Assert.Is, error: Assert failed - Is
[warning] [2023-02-14 20:31:56.039] [T-23040] [flow.hpp::451] Maybe shard Ignored an error: Assert failed - Is
```
**after**
```
LOG_shards_FORMAT=%v ./build/Release/shards docs/samples/run-sample.edn --file shards/Assert/is/2.edn
```
```
Failed assertion Is, input: 7 expected: 8
Shard activation error, failed shard: Assert.Is, error: Assert failed - Is
Maybe shard …
```
> Allow custom logging pattern

- rust/src/shards/gui/context.rs
- src/gfx/egui/egui_types.hpp
- src/gfx/egui/input.cpp
- src/gfx/egui/input.hpp
- src/gfx/egui/src/renderer.rs
Adds handling of egui outputs such as:
- clipboard
- cursor icon
- IME position
to the default `UI.Context` by passing egui outputs back to the input translator
> Add egui clipboard/cursor handling

- src/gfx/tests/CMakeLists.txt
Following changes introduced by rust-lang/rust#108262
> Explicitly link ntdll when building test-gfx on Windows

- Cargo.lock
- rust/Cargo.toml
- rust/src/shards/gui/misc/reset.rs
- rust/src/shards/gui/state.rs
- rust/src/shards/gui/widgets/code_editor/mod.rs
- rust/src/shards/gui/widgets/code_editor/syntax_highlighting.rs
- rust/src/shards/gui/widgets/console.rs
- rust/src/shards/physics/simulation.rs
- src/gfx/egui/Cargo.toml
- src/gfx/egui/src/input.rs
- src/gfx/egui/src/lib.rs
- src/gfx/egui/src/renderer.rs
- Mostly minor updates (using `cargo upgrade` and `cargo update`).
- Update `egui` to `0.21`
- Update `rapier3d` to `0.17.2`
> Update rust dependencies

- src/extra/gizmos/gizmos.cpp
- src/extra/gizmos/shapes.cpp
- src/gfx/gizmos/gizmo_input.cpp
- src/gfx/gizmos/gizmo_input.hpp
- src/gfx/gizmos/gizmo_math.hpp
- src/gfx/gizmos/gizmos.hpp
- src/gfx/gizmos/rotation_gizmo.hpp
- src/gfx/gizmos/shapes.cpp
- src/gfx/gizmos/shapes.hpp
- src/gfx/gizmos/translation_gizmo.hpp
- src/tests/gfx-gizmos-rotation.edn
This pull request adds additional functionality for ShapeRenderer to draw solid Quads and Discs (2D) and their respectively shards, as well as the RotationGizmo and its shard. Refactors Handles and its usage in TranslationGizmo.
Refer to the individual commit for comments and more details on each change to the repo in that commit.
Adjustments may need to be made in the future for the exact rotation per unit distance moved while a handle is selected.
> Add RotationGizmo

- src/gfx/gizmos/gizmo_math.hpp
- src/gfx/gizmos/shapes.cpp
- src/gfx/gizmos/shapes.hpp
- src/gfx/gizmos/translation_gizmo.hpp
Implemented three additional handles to the translation gizmo. Dragging the handles can move the object freely within a single plane (xy-plane, yz-plane or xz-plane).
**Test plan**
To test the translation gizmo, use the `src/tests/gfx-gizmos.edn` file.
> Add gizmo handles for object translation within a single plane

- docs/samples/shards/UI/Style/1.edn
- docs/samples/shards/UI/Style/2.edn
- shards/egui/src/misc/mod.rs
- shards/egui/src/misc/style.rs
- shards/egui/src/util.rs
- shards/lang/src/lib.rs
- shards/rust/src/types.rs
- shards/rust/src/util.rs
- shards/tests/ui-style.shs
Change to make the API more consistent and error checking for invalid keys.
UI.WidgetStyle now contains the WidgetVisuals  (Inactive, NonInteractive, Hovered, etc.) style tables
still not checked for table contents during compose but can be added later
> Change UI.Style to have parameters

- docs/samples/shards/UI/Selectable/1.shs
- shards/egui/src/containers/mod.rs
- shards/egui/src/containers/selectable.rs
- shards/egui/src/dnd/mod.rs
- Add custom ID parameter to drag and drop
- Change drag and drop to use the area of the whole layout it is in instead of its size in the previous frame (due to issue regarding unknown placement of next widget at cursor position)
- Fix drag and drop target rendering highlight when no drag and drop source is being dragged (but something else is being dragged. e.g. window)
- Add selectable shard (with white and grey frames for selected/not-selected states respectively)
> Fix DragAndDrop ID, response, highlight, and add Selectable shard
